ALTER TABLE public.rendasaovivo_orders 
  ADD COLUMN IF NOT EXISTS fbc TEXT,
  ADD COLUMN IF NOT EXISTS fbp TEXT,
  ADD COLUMN IF NOT EXISTS user_agent TEXT,
  ADD COLUMN IF NOT EXISTS pixel_sent BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS pixel_sent_at TIMESTAMPTZ;