ALTER TABLE public.mktcc_posts
  ADD COLUMN IF NOT EXISTS previous_media_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS previous_caption TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS revision_note TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS revision_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS revised_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE public.mktcc_projects
  ADD COLUMN IF NOT EXISTS all_approved_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS next_step_released BOOLEAN NOT NULL DEFAULT false;