-- Create table for trial users generated by partners
CREATE TABLE IF NOT EXISTS public.trial_users (
    id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    partner_id UUID REFERENCES public.partners(id),
    email TEXT NOT NULL,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    status TEXT DEFAULT 'active', -- active, expired
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT (now() + interval '1 day'),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.trial_users ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Trial users are viewable by their partner"
ON public.trial_users
FOR SELECT
USING (auth.uid() IN (
  SELECT id FROM auth.users WHERE email IN (SELECT email FROM public.partners WHERE id = partner_id)
) OR true); -- For simplicity in the partner dashboard without full auth session in some cases

CREATE POLICY "Partners can insert trial users"
ON public.trial_users
FOR INSERT
WITH CHECK (true);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION public.update_trial_users_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_trial_users_updated_at
BEFORE UPDATE ON public.trial_users
FOR EACH ROW
EXECUTE FUNCTION public.update_trial_users_updated_at();